### ISSUE TITLE
notebook example not working

### ISSUE THREAD

**Issue by RFerraciniAlves** [davebiagioni/pyomp#3]
Hello,
I tried to run the example notebook and it gives me this error msg:

name 'standardize' is not defined ( on the call of the class Result).

Is the master branch working?

**Comment by davebiagioni** [comment]
@RFerraciniAlves 

Indeed, I refactored awhile back and forgot to remove an argument to the `Result` constructor (and to test the changes!).  Should work now...

**Comment by RFerraciniAlves** [comment]
It's working. I just had to change the line 33  to work with python 3:

`for key, val in kwargs.iteritems():`

to:

`for key, val in kwargs.items():`

Thank you very much.
